import { Word } from "./types";

export const JUNIOR_ONE_SEMESTER_TWO_VOCAB: Word[] = [
  // ================= UNIT 1 =================
  {
    id: "u1_fox",
    word: "fox",
    phonetic: "/fɒks/",
    pos: "n.",
    definition: "狐狸",
    unit: 1,
    page: "p.2",
    example: "The clever fox is looking for food in the forest.",
    exampleCn: "那只聪明的狐狸正在森林里寻找食物。"
  },
  {
    id: "u1_giraffe",
    word: "giraffe",
    phonetic: "/dʒəˈrɑːf/",
    pos: "n.",
    definition: "长颈鹿",
    unit: 1,
    page: "p.2",
    example: "The giraffe uses its long neck to eat leaves from tall trees.",
    exampleCn: "长颈鹿用它长长的脖子吃高树上的叶子。"
  },
  {
    id: "u1_eagle",
    word: "eagle",
    phonetic: "/ˈiːɡl/",
    pos: "n.",
    definition: "雕；鹰",
    unit: 1,
    page: "p.2",
    example: "An eagle was flying high in the blue sky.",
    exampleCn: "一只老鹰在蔚蓝的天空中高高翱翔。"
  },
  {
    id: "u1_wolf",
    word: "wolf",
    phonetic: "/wʊlf/",
    pos: "n.",
    definition: "狼 (pl. wolves /wʊlvz/)",
    unit: 1,
    page: "p.2",
    example: "We could hear the howl of a lone wolf in the distance.",
    exampleCn: "我们能听到远处一只孤狼的嚎叫声。"
  },
  {
    id: "u1_penguin",
    word: "penguin",
    phonetic: "/ˈpeŋɡwɪn/",
    pos: "n.",
    definition: "企鹅",
    unit: 1,
    page: "p.2",
    example: "Penguins are birds that can swim but cannot fly.",
    exampleCn: "企鹅是会游泳但不会飞的鸟类。"
  },
  {
    id: "u1_care",
    word: "care",
    phonetic: "/keə(r)/",
    pos: "n. & v.",
    definition: "照顾；护理；关心；在乎",
    unit: 1,
    page: "p.2",
    example: "Parents always care about their children's future.",
    exampleCn: "父母总是关心他们孩子的未来。"
  },
  {
    id: "u1_sandwich",
    word: "sandwich",
    phonetic: "/ˈsænwɪtʃ/",
    pos: "n.",
    definition: "三明治",
    unit: 1,
    page: "p.3",
    example: "I will make a ham and vegetable sandwich for lunch.",
    exampleCn: "我午饭要准备一个火腿蔬菜三明治。"
  },
  {
    id: "u1_snake",
    word: "snake",
    phonetic: "/sneɪk/",
    pos: "n.",
    definition: "蛇",
    unit: 1,
    page: "p.5",
    example: "Some people are afraid of snakes because some can be poisonous.",
    exampleCn: "有些人害怕蛇，因为有些蛇可能有毒。"
  },
  {
    id: "u1_scary",
    word: "scary",
    phonetic: "/ˈskeəri/",
    pos: "adj.",
    definition: "吓人的；恐怖的",
    unit: 1,
    page: "p.5",
    example: "We watched a very scary movie last night.",
    exampleCn: "我们昨晚看了一部非常恐怖的电影。"
  },
  {
    id: "u1_guess",
    word: "guess",
    phonetic: "/ɡes/",
    pos: "v.",
    definition: "猜测；估计",
    unit: 1,
    page: "p.5",
    example: "Can you guess how many pandas live in this nature reserve?",
    exampleCn: "你能猜出这个自然保护区里生活着多少只大熊猫吗？"
  },
  {
    id: "u1_shark",
    word: "shark",
    phonetic: "/ʃɑːk/",
    pos: "n.",
    definition: "鲨鱼",
    unit: 1,
    page: "p.5",
    example: "Sharks are among the oldest creatures on Earth.",
    exampleCn: "鲨鱼是地球上最古老的生物之一。"
  },
  {
    id: "u1_dangerous",
    word: "dangerous",
    phonetic: "/ˈdeɪndʒərəs/",
    pos: "adj.",
    definition: "危险的；有危害的",
    unit: 1,
    page: "p.5",
    example: "It is dangerous to play with fire matches.",
    exampleCn: "玩火柴是很危险的。"
  },
  {
    id: "u1_save",
    word: "save",
    phonetic: "/seɪv/",
    pos: "v.",
    definition: "救；储蓄；保存",
    unit: 1,
    page: "p.6",
    example: "We need to save water in our daily lives.",
    exampleCn: "我们在日常生活中需要节约用水。"
  },
  {
    id: "u1_friendly",
    word: "friendly",
    phonetic: "/ˈfrendli/",
    pos: "adj.",
    definition: "友好的",
    unit: 1,
    page: "p.7",
    example: "Our new English teacher is very friendly to everyone.",
    exampleCn: "我们的新英语老师对每个人都非常友好。"
  },

  // ================= UNIT 2 =================
  {
    id: "u2_rule",
    word: "rule",
    phonetic: "/ruːl/",
    pos: "n.",
    definition: "规则；规章",
    unit: 2,
    page: "p.9",
    example: "We must follow the school rules and not run in the hallways.",
    exampleCn: "我们必须遵守学校规章，不要在走廊里跑动。"
  },
  {
    id: "u2_order",
    word: "order",
    phonetic: "/ˈɔːdə(r)/",
    pos: "n. & v.",
    definition: "秩序；命令；点菜",
    unit: 2,
    page: "p.9",
    example: "May I take your order now, sir?",
    exampleCn: "先生，现在可以为您点菜了吗？"
  },
  {
    id: "u2_follow",
    word: "follow",
    phonetic: "/ˈfɒləʊ/",
    pos: "v.",
    definition: "遵循；跟随",
    unit: 2,
    page: "p.10",
    example: "Follow me, and I will show you the correct way.",
    exampleCn: "跟着我，我会指给你正确的路。"
  },
  {
    id: "u2_arrive",
    word: "arrive",
    phonetic: "/əˈraɪv/",
    pos: "v.",
    definition: "到达",
    unit: 2,
    page: "p.10",
    example: "The school bus will arrive at exactly seven o'clock.",
    exampleCn: "校车将在七点准时到达。"
  },
  {
    id: "u2_on_time",
    word: "on time",
    phonetic: "/ɒn taɪm/",
    pos: "phrase",
    definition: "准时",
    unit: 2,
    page: "p.10",
    example: "Please make sure you get to the library on time.",
    exampleCn: "请务必准时到达图书馆。"
  },
  {
    id: "u2_uniform",
    word: "uniform",
    phonetic: "/ˈjuːnɪfɔːm/",
    pos: "n.",
    definition: "校服；制服",
    unit: 2,
    page: "p.10",
    example: "Students are required to wear a school uniform on Mondays.",
    exampleCn: "学生们被要求在周一穿着校服。"
  },
  {
    id: "u2_litter",
    word: "litter",
    phonetic: "/ˈlɪtə(r)/",
    pos: "v. & n.",
    definition: "乱扔；垃圾",
    unit: 2,
    page: "p.10",
    example: "Don't litter in public parks; put trash in the bins.",
    exampleCn: "不要在公园等公共场合乱扔垃圾；请放入垃圾桶内。"
  },
  {
    id: "u2_polite",
    word: "polite",
    phonetic: "/pəˈlaɪt/",
    pos: "adj.",
    definition: "有礼貌的",
    unit: 2,
    page: "p.10",
    example: "It is polite to say 'thank you' when others help you.",
    exampleCn: "当别人帮助你时，说‘谢谢’是有礼貌的表现。"
  },
  {
    id: "u2_respect",
    word: "respect",
    phonetic: "/rɪˈspekt/",
    pos: "n. & v.",
    definition: "尊敬；尊重",
    unit: 2,
    page: "p.10",
    example: "We should respect our teachers and elder family members.",
    exampleCn: "我们应当尊敬老师和年长的家庭成员。"
  },
  {
    id: "u2_have_to",
    word: "have to",
    phonetic: "/hæv tu/",
    pos: "phrase",
    definition: "不得不；必须",
    unit: 2,
    page: "p.10",
    example: "I have to finish my English homework before dinner.",
    exampleCn: "我有必要在晚饭前写完我的英语功课。"
  },
  {
    id: "u2_relax",
    word: "relax",
    phonetic: "/rɪˈlæks/",
    pos: "v.",
    definition: "放松；休息",
    unit: 2,
    page: "p.14",
    example: "Let's listen to some music to relax after class.",
    exampleCn: "下课后，让我们听点音乐放松一下吧。"
  },
  {
    id: "u2_understand",
    word: "understand",
    phonetic: "/ˌʌndəˈstænd/",
    pos: "v.",
    definition: "理解；领会",
    unit: 2,
    page: "p.15",
    example: "Do you understand what she meant by that comment?",
    exampleCn: "你理解她那句话的意思吗？"
  },

  // ================= UNIT 3 =================
  {
    id: "u3_fit",
    word: "fit",
    phonetic: "/fɪt/",
    pos: "adj. & v.",
    definition: "健康的；健壮的；适合",
    unit: 3,
    page: "p.17",
    example: "Running and eating healthy food keeps us fit.",
    exampleCn: "跑步和吃健康的食物可以让我们保持健康。"
  },
  {
    id: "u3_baseball",
    word: "baseball",
    phonetic: "/ˈbeɪsbɔːl/",
    pos: "n.",
    definition: "棒球（运动）",
    unit: 3,
    page: "p.18",
    example: "We played baseball in the playground last weekend.",
    exampleCn: "上个周末，我们在操场上打了棒球。"
  },
  {
    id: "u3_glove",
    word: "glove",
    phonetic: "/ɡlʌv/",
    pos: "n.",
    definition: "（手指分开的）手套",
    unit: 3,
    page: "p.18",
    example: "You need a thick leather glove to catch the baseball safely.",
    exampleCn: "你需要一只厚皮手套才能安全地接住棒球。"
  },
  {
    id: "u3_rope",
    word: "rope",
    phonetic: "/rəʊp/",
    pos: "n.",
    definition: "绳子；粗绳",
    unit: 3,
    page: "p.18",
    example: "The sailors stored a heavy rope on the deck of the boat.",
    exampleCn: "水手们在船甲板上放了一条重重的粗绳。"
  },
  {
    id: "u3_hardly",
    word: "hardly",
    phonetic: "/ˈhɑːdli/",
    pos: "adv.",
    definition: "几乎不；几乎没有",
    unit: 3,
    page: "p.18",
    example: "I can hardly hear what she is saying from the back row.",
    exampleCn: "我坐在后排几乎听不见她在说什么。"
  },
  {
    id: "u3_once",
    word: "once",
    phonetic: "/wʌns/",
    pos: "adv. & conj.",
    definition: "一次；曾经；一旦",
    unit: 3,
    page: "p.18",
    example: "Our family goes to the science museum once a month.",
    exampleCn: "我们全家每个月去一次科学博物馆。"
  },
  {
    id: "u3_twice",
    word: "twice",
    phonetic: "/twaɪs/",
    pos: "adv.",
    definition: "两次；两倍",
    unit: 3,
    page: "p.18",
    example: "He brushes his teeth twice a day—once in the morning and once at night.",
    exampleCn: "他每天刷牙两次——早晚各一次。"
  },
  {
    id: "u3_practice",
    word: "practice",
    phonetic: "/ˈpræktɪs/",
    pos: "n.",
    definition: "练习；实践",
    unit: 3,
    page: "p.19",
    example: "Practice makes perfect when learning a new language.",
    exampleCn: "学习一门新语言时，熟能生巧。"
  },
  {
    id: "u3_badminton",
    word: "badminton",
    phonetic: "/ˈbædmɪntən/",
    pos: "n.",
    definition: "羽毛球运动",
    unit: 3,
    page: "p.19",
    example: "Playing badminton is a great way to exercise our eyes.",
    exampleCn: "打羽毛球是锻炼我们眼睛极佳的方法。"
  },
  {
    id: "u3_belong_to",
    word: "belong to",
    phonetic: "/bɪˈlɒŋ tu/",
    pos: "phrase",
    definition: "属于（某人）",
    unit: 3,
    page: "p.21",
    example: "Does this red pencil box belong to you, Linda?",
    exampleCn: "琳达，这个红色的铅笔盒是你的吗？"
  },
  {
    id: "u3_encourage",
    word: "encourage",
    phonetic: "/ɪnˈkʌrɪdʒ/",
    pos: "v.",
    definition: "鼓励；激励",
    unit: 3,
    page: "p.22",
    example: "Our teacher encourages us to speak English as much as possible.",
    exampleCn: "我们的老师鼓励我们尽可能多说英语。"
  },
  {
    id: "u3_goal",
    word: "goal",
    phonetic: "/ɡəʊl/",
    pos: "n.",
    definition: "目标；目的；进球",
    unit: 3,
    page: "p.22",
    example: "My primary goal this term is to speak English fluently.",
    exampleCn: "我这学期的主要目标是说一口流利的英语。"
  },

  // ================= UNIT 4 =================
  {
    id: "u4_watermelon",
    word: "watermelon",
    phonetic: "/ˈwɔːtəmelən/",
    pos: "n.",
    definition: "西瓜",
    unit: 4,
    page: "p.26",
    example: "Eating sweet, cold watermelon is wonderful in hot summer.",
    exampleCn: "在炎热的夏天吃甜甜凉凉的西瓜真是棒极了。"
  },
  {
    id: "u4_mutton",
    word: "mutton",
    phonetic: "/ˈmʌtn/",
    pos: "n.",
    definition: "羊肉",
    unit: 4,
    page: "p.26",
    example: "The mutton soup warmed us up quickly on that cold evening.",
    exampleCn: "在寒冷的夜晚，这热腾腾的羊肉汤让我们很快暖和了起来。"
  },
  {
    id: "u4_cookie",
    word: "cookie",
    phonetic: "/ˈkʊki/",
    pos: "n.",
    definition: "曲奇饼；饼干",
    unit: 4,
    page: "p.26",
    example: "My grandmother baked some delicious chocolate chip cookies for us.",
    exampleCn: "我祖母为我们烤了一些美味的巧克力豆曲奇饼。"
  },
  {
    id: "u4_dumpling",
    word: "dumpling",
    phonetic: "/ˈdʌmplɪŋ/",
    pos: "n.",
    definition: "饺子",
    unit: 4,
    page: "p.26",
    example: "Making dumplings is a happy family tradition during Lunar New Year.",
    exampleCn: "农历新年期间包饺子是幸福的家庭传统。"
  },
  {
    id: "u4_salad",
    word: "salad",
    phonetic: "/ˈsæləd/",
    pos: "n.",
    definition: "沙拉；色拉",
    unit: 4,
    page: "p.26",
    example: "She likes adding tomatoes and cucumber to her fresh green salad.",
    exampleCn: "她喜欢在新鲜的绿叶沙拉中加入番茄和黄瓜。"
  },
  {
    id: "u4_taste",
    word: "taste",
    phonetic: "/teɪst/",
    pos: "v. & n.",
    definition: "有……味道；尝；味道",
    unit: 4,
    page: "p.27",
    example: "The fresh orange juice tastes sweet and sour.",
    exampleCn: "新鲜的橙汁尝起来酸酸甜甜的。"
  },
  {
    id: "u4_choice",
    word: "choice",
    phonetic: "/tʃɔɪs/",
    pos: "n.",
    definition: "选择",
    unit: 4,
    page: "p.28",
    example: "You have a choice between fresh fruit or ice cream for dessert.",
    exampleCn: "对于甜点，你可以选择新鲜水果或者冰淇淋。"
  },
  {
    id: "u4_strawberry",
    word: "strawberry",
    phonetic: "/ˈstrɔːbəri/",
    pos: "n.",
    definition: "草莓",
    unit: 4,
    page: "p.28",
    example: "We picked sweet strawberries from the local farm last winter.",
    exampleCn: "去年冬天，我们从当地农场摘了些甜美可口的草莓。"
  },
  {
    id: "u4_instead",
    word: "instead",
    phonetic: "/ɪnˈsted/",
    pos: "adv.",
    definition: "反而；代替",
    unit: 4,
    page: "p.29",
    example: "If there is no school bus today, we can walk home instead.",
    exampleCn: "如果今天没有校车，我们可以步行回家来代替。"
  },
  {
    id: "u4_improve",
    word: "improve",
    phonetic: "/ɪmˈpruːv/",
    pos: "v.",
    definition: "改进；改善；提高",
    unit: 4,
    page: "p.30",
    example: "Regular practice will help you improve your English spelling.",
    exampleCn: "定期练习可以帮助你提高英语单词的拼写能力。"
  },
  {
    id: "u4_habit",
    word: "habit",
    phonetic: "/ˈhæbɪt/",
    pos: "n.",
    definition: "习惯",
    unit: 4,
    page: "p.30",
    example: "Reading daily is an excellent habit that helps you think better.",
    exampleCn: "每日阅读是一种绝佳的习惯，有助于更好地思考。"
  },
  {
    id: "u4_balanced",
    word: "balanced",
    phonetic: "/ˈbælənst/",
    pos: "adj.",
    definition: "均衡的；平衡的",
    unit: 4,
    page: "p.30",
    example: "A balanced diet should include meat, vegetables, and grains.",
    exampleCn: "均衡的饮食应当包含肉类、蔬菜和谷物。"
  },

  // ================= UNIT 5 =================
  {
    id: "u5_right_now",
    word: "right now",
    phonetic: "/raɪt naʊ/",
    pos: "phrase",
    definition: "现在；立刻",
    unit: 5,
    page: "p.34",
    example: "I need you to show me your homework right now.",
    exampleCn: "我现在需要你把你的作业拿给我看。"
  },
  {
    id: "u5_moment",
    word: "moment",
    phonetic: "/ˈməʊmənt/",
    pos: "n.",
    definition: "某个时刻；片刻",
    unit: 5,
    page: "p.34",
    example: "Please wait a moment while I check the dictionary.",
    exampleCn: "在我查阅词典时，请稍微等候片刻。"
  },
  {
    id: "u5_festival",
    word: "festival",
    phonetic: "/ˈfestɪvl/",
    pos: "n.",
    definition: "节日",
    unit: 5,
    page: "p.35",
    example: "The Mid-Autumn Festival is when families gather to enjoy the moon.",
    exampleCn: "中秋节是家人团聚赏月的时候。"
  },
  {
    id: "u5_hold",
    word: "hold",
    phonetic: "/həʊld/",
    pos: "v.",
    definition: "拿着；抓住；举行",
    unit: 5,
    page: "p.35",
    example: "Can you hold this heavy bag of sweet pears for me, please?",
    exampleCn: "请问你能帮我拿一下这包重重的甜梨子吗？"
  },
  {
    id: "u5_voice",
    word: "voice",
    phonetic: "/vɔɪs/",
    pos: "n.",
    definition: "嗓音；声音",
    unit: 5,
    page: "p.35",
    example: "Our English teacher speaks with a soft and clear voice.",
    exampleCn: "我们的英语老师用温柔细腻且清晰的声音说话。"
  },
  {
    id: "u5_message",
    word: "message",
    phonetic: "/ˈmesɪdʒ/",
    pos: "n.",
    definition: "消息；信息",
    unit: 5,
    page: "p.36",
    example: "Can I leave a message for your father, Tony?",
    exampleCn: "托尼，我能给你爸爸留个话吗？"
  },
  {
    id: "u5_online",
    word: "online",
    phonetic: "/ˌɒnˈlaɪn/",
    pos: "adj. & adv.",
    definition: "在线的；在网上",
    unit: 5,
    page: "p.37",
    example: "There are many online games that can help us read English books.",
    exampleCn: "网上有许多辅助我们阅读英语书的游戏。"
  },
  {
    id: "u5_look_forward_to",
    word: "look forward to",
    phonetic: "/lʊk ˈfɔːwəd tu/",
    pos: "phrase",
    definition: "盼望；期待",
    unit: 5,
    page: "p.37",
    example: "I look forward to visiting the museum during the Dragon Boat Festival.",
    exampleCn: "我非常盼望端午节期间可以去参观博物馆。"
  },
  {
    id: "u5_rush",
    word: "rush",
    phonetic: "/rʌʃ/",
    pos: "v. & n.",
    definition: "冲；奔；急忙",
    unit: 5,
    page: "p.38",
    example: "Don't rush; we still have thirty minutes before the train leaves.",
    exampleCn: "别着急，在火车开动前我们还有三十分钟。"
  },
  {
    id: "u5_slowly",
    word: "slowly",
    phonetic: "/ˈsləʊli/",
    pos: "adv.",
    definition: "缓慢地",
    unit: 5,
    page: "p.38",
    example: "Snail moves very slowly on green leaves.",
    exampleCn: "蜗牛在绿叶上移动得非常缓慢。"
  },
  {
    id: "u5_subway",
    word: "subway",
    phonetic: "/ˈsʌbweɪ/",
    pos: "n.",
    definition: "地铁",
    unit: 5,
    page: "p.38",
    example: "The subway is fast, clean, and never stuck in traffic jams.",
    exampleCn: "地铁速度极快、干净卫生、且永远不会遭遇塞车。"
  },

  // ================= UNIT 6 =================
  {
    id: "u6_affect",
    word: "affect",
    phonetic: "/əˈfekt/",
    pos: "v.",
    definition: "影响",
    unit: 6,
    page: "p.41",
    example: "Extremely cold weather always affects the growth of fresh plants.",
    exampleCn: "极寒冷的天气总会影响新鲜植物的生长。"
  },
  {
    id: "u6_dry",
    word: "dry",
    phonetic: "/draɪ/",
    pos: "adj. & v.",
    definition: "干的；干旱的；使变干",
    unit: 6,
    page: "p.42",
    example: "The air is very dry during winter in northern China.",
    exampleCn: "中国北方的冬季空气非常干燥。"
  },
  {
    id: "u6_lightning",
    word: "lightning",
    phonetic: "/ˈlaɪtnɪŋ/",
    pos: "n.",
    definition: "闪电",
    unit: 6,
    page: "p.42",
    example: "A blinding flash of lightning lit up the stormy dark sky.",
    exampleCn: "一道刺眼的闪电照亮了暴风雨肆虐的夜空。"
  },
  {
    id: "u6_stormy",
    word: "stormy",
    phonetic: "/ˈstɔːmi/",
    pos: "adj.",
    definition: "有暴风雨的",
    unit: 6,
    page: "p.42",
    example: "The fishermen decided not to sail away on such a stormy day.",
    exampleCn: "渔夫们在这个暴风雨天决定不出海航行了。"
  },
  {
    id: "u6_lucky",
    word: "lucky",
    phonetic: "/ˈlʌki/",
    pos: "adj.",
    definition: "运气好的；幸运的",
    unit: 6,
    page: "p.43",
    example: "Seven is often considered a lucky number in many Western countries.",
    exampleCn: "在许多西方国家，‘七’通常被看作是一个幸运数字。"
  },
  {
    id: "u6_temperature",
    word: "temperature",
    phonetic: "/ˈtemprətʃə(r)/",
    pos: "n.",
    definition: "温度",
    unit: 6,
    page: "p.44",
    example: "The temperature has dropped severely since the stormy clouds arrived.",
    exampleCn: "自暴风雨云团来临之后，温度已经急剧下降。"
  },
  {
    id: "u6_snowman",
    word: "snowman",
    phonetic: "/ˈsnəʊmæn/",
    pos: "n.",
    definition: "雪人 (pl. snowmen)",
    unit: 6,
    page: "p.44",
    example: "The children gathered to make a funny snowman with a carrot nose.",
    exampleCn: "孩子们聚在一起做了一个长着胡萝卜鼻子的滑稽雪人。"
  },
  {
    id: "u6_snowy",
    word: "snowy",
    phonetic: "/ˈsnəʊi/",
    pos: "adj.",
    definition: "下雪的；雪白的",
    unit: 6,
    page: "p.45",
    example: "I love watching snowy mountains under pure bright sunlight.",
    exampleCn: "我喜欢欣赏纯净、明亮的阳光下那些白雪皑皑的山峰。"
  },
  {
    id: "u6_cloud",
    word: "cloud",
    phonetic: "/klaʊd/",
    pos: "n.",
    definition: "云；云彩",
    unit: 6,
    page: "p.46",
    example: "Look at that big white cloud that looks exactly like a playful giraffe!",
    exampleCn: "看那朵白白的大云彩，长得简直像一只爱嬉戏的长颈鹿！"
  },
  {
    id: "u6_make_progress",
    word: "make progress",
    phonetic: "/meɪk ˈprəʊɡres/",
    pos: "phrase",
    definition: "取得进展；有进步",
    unit: 6,
    page: "p.46",
    example: "She has made great progress in her English pronunciation this term.",
    exampleCn: "这学期她在英语音标发音上取得了巨大进步。"
  },
  {
    id: "u6_although",
    word: "although",
    phonetic: "/ɔːlˈðəʊ/",
    pos: "conj.",
    definition: "虽然；尽管",
    unit: 6,
    page: "p.46",
    example: "Although it was raining heavily, the students still arrived on time.",
    exampleCn: "尽管雨下得很大，同学们依然准时到了。"
  },
  {
    id: "u6_mountain",
    word: "mountain",
    phonetic: "/ˈmaʊntən/",
    pos: "n.",
    definition: "山；高山",
    unit: 6,
    page: "p.47",
    example: "Climbing that high mountain is very tiring but completely worth it.",
    exampleCn: "爬上那座高山是非常令人疲惫的，但完全值得。"
  },

  // ================= UNIT 7 =================
  {
    id: "u7_meet_up",
    word: "meet up",
    phonetic: "/miːt ʌp/",
    pos: "phrase",
    definition: "相聚；碰头",
    unit: 7,
    page: "p.50",
    example: "Let's meet up outside the history museum tomorrow at ten.",
    exampleCn: "明天十点我们让在历史博物馆外面碰头。"
  },
  {
    id: "u7_museum",
    word: "museum",
    phonetic: "/mjuˈziːəm/",
    pos: "n.",
    definition: "博物馆",
    unit: 7,
    page: "p.50",
    example: "There is an exhibition of dinosaur bones inside the national museum.",
    exampleCn: "国家博物馆里正在举办恐龙遗骸的展出。"
  },
  {
    id: "u7_direction",
    word: "direction",
    phonetic: "/daɪˈrekʃn/",
    pos: "n.",
    definition: "方向",
    unit: 7,
    page: "p.50",
    example: "Could you tell me which direction I should take for the subway station?",
    exampleCn: "请问去地铁站我应该走哪个方向？"
  },
  {
    id: "u7_trip",
    word: "trip",
    phonetic: "/trɪp/",
    pos: "n.",
    definition: "旅行；行程",
    unit: 7,
    page: "p.51",
    example: "Have a safe and wonderful weekend trip with your family!",
    exampleCn: "祝你与家人周末旅途愉快平安！"
  },
  {
    id: "u7_remove",
    word: "remove",
    phonetic: "/rɪˈmuːv/",
    pos: "v.",
    definition: "移开；拿走",
    unit: 7,
    page: "p.51",
    example: "Please remove the dry leaves from the swimming pool.",
    exampleCn: "请把游泳池里的枯叶清理拿走。"
  },
  {
    id: "u7_step",
    word: "step",
    phonetic: "/step/",
    pos: "n. & v.",
    definition: "步骤；脚印；跨步",
    unit: 7,
    page: "p.51",
    example: "Following the instructions step by step is crucial to build this model.",
    exampleCn: "一步一步遵循说明书对于建造这个模型至关重要。"
  },
  {
    id: "u7_realize",
    word: "realize",
    phonetic: "/ˈrɪəlaɪz/",
    pos: "v.",
    definition: "认识到；明白；实现",
    unit: 7,
    page: "p.51",
    example: "I didn't realize how late it was and almost missed my curfew.",
    exampleCn: "我没有意识到时间已经这么晚了，险些错过了宵禁。"
  },
  {
    id: "u7_create",
    word: "create",
    phonetic: "/kriˈeɪt/",
    pos: "v.",
    definition: "创造；创作",
    unit: 7,
    page: "p.53",
    example: "Artists use paint brushes to create beautiful colored canvases.",
    exampleCn: "美术家用画笔创作出绚丽多姿的作品。"
  },
  {
    id: "u7_record",
    word: "record",
    phonetic: "/rɪˈkɔːd/",
    pos: "v. & n.",
    definition: "记录；录制",
    unit: 7,
    page: "p.54",
    example: "Write down everything so you can record your dairy entries safely.",
    exampleCn: "把所有事都写下来，这样你就能妥善记录你的日记条目了。"
  },
  {
    id: "u7_skill",
    word: "skill",
    phonetic: "/skɪl/",
    pos: "n.",
    definition: "技能；技巧",
    unit: 7,
    page: "p.54",
    example: "Spelling words correctly is an essential skill in English classes.",
    exampleCn: "正确拼写单词是英语课上的一项基本技能。"
  },
  {
    id: "u7_finally",
    word: "finally",
    phonetic: "/ˈfaɪnəli/",
    pos: "adv.",
    definition: "终于；最后",
    unit: 7,
    page: "p.54",
    example: "After three hours of exhausting climbing, we finally reached the top.",
    exampleCn: "经过了三小时极其劳累的攀登，我们终于到达了山顶。"
  },
  {
    id: "u7_diary",
    word: "diary",
    phonetic: "/ˈdaɪəri/",
    pos: "n.",
    definition: "日记",
    unit: 7,
    page: "p.55",
    example: "She keeping a diary which helps her practice her writing skills daily.",
    exampleCn: "她有写日记的习惯，这有助于她每天练习写作技巧。"
  },

  // ================= UNIT 8 =================
  {
    id: "u8_promise",
    word: "promise",
    phonetic: "/ˈpɒmɪs/",
    pos: "v. & n.",
    definition: "承诺；保证",
    unit: 8,
    page: "p.58",
    example: "Don't make a promise to anyone unless you are sure you can keep it.",
    exampleCn: "除非确保能够做到，不然不要向任何人许下承诺。"
  },
  {
    id: "u8_neighbour",
    word: "neighbour",
    phonetic: "/ˈneɪbə(r)/",
    pos: "n.",
    definition: "邻居",
    unit: 8,
    page: "p.58",
    example: "Our next-door neighbour is a friendly doctor working in a local clinic.",
    exampleCn: "我们隔壁的邻居是当地一家诊所工作的友好医生。"
  },
  {
    id: "u8_wise",
    word: "wise",
    phonetic: "/waɪz/",
    pos: "adj.",
    definition: "明智的；高明的",
    unit: 8,
    page: "p.58",
    example: "It is wise to study ahead and prepare before the unit exams.",
    exampleCn: "在单元考试前提前学习并做准备，这是很明智的。"
  },
  {
    id: "u8_emperor",
    word: "emperor",
    phonetic: "/ˈempərə(r)/",
    pos: "n.",
    definition: "皇帝",
    unit: 8,
    page: "p.59",
    example: "We read a classic fairy tale about an emperor and his new clothes.",
    exampleCn: "我们读了一个关于皇帝和他的新装的经典童话故事。"
  },
  {
    id: "u8_pretend",
    word: "pretend",
    phonetic: "/prɪˈtend/",
    pos: "v.",
    definition: "假装；伪装",
    unit: 8,
    page: "p.59",
    example: "The girls love to pretend they are princesses living in huge castles.",
    exampleCn: "女孩们非常喜欢假装自己是居住在巨大城堡里的公主。"
  },
  {
    id: "u8_silly",
    word: "silly",
    phonetic: "/ˈsɪli/",
    pos: "adj.",
    definition: "愚蠢的；傻里傻气的",
    unit: 8,
    page: "p.59",
    example: "I felt very silly when I wore my slippers to the classroom.",
    exampleCn: "当我穿着拖鞋走进教室时，我觉得自己非常蠢蠢的。"
  },
  {
    id: "u8_decide",
    word: "decide",
    phonetic: "/dɪˈsaɪd/",
    pos: "v.",
    definition: "决定；下决心",
    unit: 8,
    page: "p.59",
    example: "Did you decide which book to read for the upcoming book report?",
    exampleCn: "你决定好了下一次读书报告要读哪本书了吗？"
  },
  {
    id: "u8_praise",
    word: "praise",
    phonetic: "/preɪz/",
    pos: "v. & n.",
    definition: "赞美；表扬",
    unit: 8,
    page: "p.59",
    example: "Parents should frequently praise their kids for trying their absolute best.",
    exampleCn: "父母应该经常表扬孩子付出的全力以赴的尝试。"
  },
  {
    id: "u8_afraid",
    word: "afraid",
    phonetic: "/əˈfreɪd/",
    pos: "adj.",
    definition: "害怕的；担心的",
    unit: 8,
    page: "p.59",
    example: "He is afraid of the dark and likes sleeping with a little light on.",
    exampleCn: "他怕黑，所以喜欢亮着一点微弱的光睡觉。"
  },
  {
    id: "u8_suddenly",
    word: "suddenly",
    phonetic: "/ˈsʌdənli/",
    pos: "adv.",
    definition: "突然地",
    unit: 8,
    page: "p.59",
    example: "Suddenly, a tiny blue bird flew through the open classroom window.",
    exampleCn: "突然，一只小小的蓝色小鸟飞进了敞开着的教室窗户。"
  },
  {
    id: "u8_truth",
    word: "truth",
    phonetic: "/truːθ/",
    pos: "n.",
    definition: "真相；事实；真理",
    unit: 8,
    page: "p.60",
    example: "It is always best to tell the truth even when it makes you nervous.",
    exampleCn: "真诚讲出事实真相总归是最好的，即便那会让你有些紧张。"
  },
  {
    id: "u8_artist",
    word: "artist",
    phonetic: "/ˈɑːtɪst/",
    pos: "n.",
    definition: "美术家；艺术家",
    unit: 8,
    page: "p.61",
    example: "The talented artist painted a vivid picture of the snowy mountain peak.",
    exampleCn: "这位才华横溢的艺术家画了一幅色彩生动的雪山山巅画作。"
  }
];
